### ISSUE TITLE
when i run :python run.py,it has some problem.What is wrong with me？I use 1070Ti

### ISSUE THREAD

**Issue by zhaowuyao** [liorsidi/ViolenceDetection_CNNLSTM#2]
tcmalloc: large alloc 2857730048 bytes == (nil) @ 
Traceback (most recent call last):
  File "run.py", line 230, in <module>
    classes=classes, use_augs=use_augs, fix_lens=fix_lens)
  File "run.py", line 166, in hyper_tune_network
    classes=classes)
  File "run.py", line 112, in get_generators
    classes=classes)
  File "/home/zhaowuyao/disk_a/ViolenceDetection_CNNLSTM-master/DatasetBuilder.py", line 221, in get_sequences
    X = pad_sequences(X, maxlen=seq_length, padding='pre', truncating='pre')
  File "/home/zhaowuyao/disk_a/anaconda3/envs/py2/lib/python2.7/site-packages/keras_preprocessing/sequence.py", line 81, in pad_sequences
    x = np.full((num_samples, maxlen) + sample_shape, value, dtype=dtype)
  File "/home/zhaowuyao/disk_a/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/numeric.py", line 309, in full
    a = empty(shape, dtype, order)
MemoryError

**Comment by liorsidi** [comment]
Hey!
Maybe you entered a full video, which has too many frames?
1. You can preprocess the video to smaller sequences, and then apply the model on each sequence separately
2. Consider using a data generator for training and applying the model so you won't get a memory error
